import type { Article, Podcast } from "./types";

export const ARTICLES: Article[] = [
  // ── SÉNÉGAL ──
  {
    slug: "saint-louis-peche-artisanale",
    title: "À Saint-Louis, le bras de fer monte d'un cran autour de la pêche artisanale",
    dek: "Depuis l'aube, plus de quatre cents pirogues bloquent l'accès au port de Guet Ndar pour protester contre la signature de nouveaux accords avec les chalutiers étrangers.",
    rubrique: "senegal",
    rubriqueLabel: "Sénégal · Saint-Louis",
    author: "Aïssatou Ndoye",
    date: "Aujourd'hui · 11h30",
    dateIso: "2026-05-07T11:30",
    readTime: "8 min",
    imgSeed: "saintlouis-pirogues",
    imgAlt: "Pirogues à Saint-Louis, Guet Ndar",
    badge: "rep",
    featured: true,
    commentCount: 6,
    tags: ["Sénégal", "Saint-Louis", "Pêche artisanale", "Économie maritime", "Accords de pêche", "Guet Ndar"],
    authorBio: "Grand reporter spécialisée dans les questions environnementales et d'économie bleue. Basée à Dakar, elle couvre l'Afrique de l'Ouest pour À l'Heure depuis 2019.",
    body: [
      { type: "p", text: "Il est à peine cinq heures du matin quand les premières pirogues se mettent en travers du chenal. En quelques dizaines de minutes, elles sont plus de quatre cents à former un verrou silencieux sur les eaux sombres du fleuve Sénégal, à l'entrée du port de Guet Ndar. Les hommes sont debout, debout depuis la veille pour certains. Ils ne crient pas. Ils attendent." },
      { type: "p", text: "« On n'a plus le choix », dit Lamine Ndiaye, 54 ans, les mains posées sur l'étrave de sa pirogue peinte en bleu et blanc. Pêcheur depuis l'enfance, il a connu les temps où les eaux débordaient de thons et de capitaines. Depuis dix ans, il dit que « la mer s'est appauvrie ». Et il en tient responsables les chalutiers étrangers — européens, asiatiques — qui raclent les fonds à des profondeurs interdites." },
      { type: "h2", text: "La goutte qui a fait déborder le fleuve" },
      { type: "p", text: "Ce qui a mis le feu aux poudres, c'est la publication, il y a trois jours, d'un document gouvernemental annonçant la signature de deux nouveaux protocoles d'accord avec des armements basés en Espagne et en Chine. Ces accords permettraient à des navires de plus de 1 500 tonnes d'opérer dans la zone économique exclusive sénégalaise jusqu'à soixante-dix milles des côtes — soit, selon les syndicats de pêcheurs, dans des zones historiquement réservées à la pêche artisanale côtière." },
      { type: "p", text: "Le Collectif des Mareyeurs et Pêcheurs du Fleuve, réuni en urgence le lendemain, a voté à l'unanimité le blocage du port. Une décision « douloureuse mais nécessaire », selon son secrétaire général, Ibrahima Sarr. « Nous perdons nos revenus, nos familles souffrent. Mais si nous ne bloquons pas aujourd'hui, il ne restera plus rien demain. »" },
      { type: "blockquote", text: "« Si nous ne bloquons pas aujourd'hui, il ne restera plus rien demain. »", cite: "Ibrahima Sarr, secrétaire général du Collectif des Mareyeurs et Pêcheurs du Fleuve" },
      { type: "h2", text: "L'État entre pression économique et engagements internationaux" },
      { type: "p", text: "Du côté gouvernemental, le silence a duré plusieurs heures avant qu'un communiqué du ministère de la Pêche ne reconnaisse « la légitimité des préoccupations soulevées » tout en défendant les accords comme « essentiels à l'équilibre des finances publiques ». Selon des sources proches des négociations qu'À l'Heure a pu consulter, les deux protocoles représentent une contrepartie de l'ordre de 14 milliards de francs CFA par an pour le Trésor sénégalais." },
      { type: "p", text: "Un chiffre qui ne convainc pas les pêcheurs. « Quatorze milliards pour détruire une filière qui fait vivre directement 600 000 personnes au Sénégal ? C'est du bradage pur », tranche Astou Diallo, présidente de l'Association des Femmes Transformatrices de Poisson de Saint-Louis. Les femmes transformatrices — qui sèchent, fument et commercialisent les prises — sont en première ligne de la crise : sans poisson, pas de transformation, pas de revenus." },
      { type: "pullquote", text: "Quatre cents pirogues, trois cents familles au bord de la rupture. Saint-Louis attend que l'État choisisse entre une rente et un patrimoine." },
      { type: "h2", text: "Ce que réclament les pêcheurs" },
      { type: "p", text: "Le Collectif a formalisé ses demandes en trois points : la suspension immédiate de la signature des deux protocoles dans l'attente d'un audit indépendant, la création d'une commission mixte chargée de redéfinir les zones de pêche autorisées, et une compensation financière pour les pertes subies depuis six mois." },
      { type: "p", text: "La pêche artisanale représente 75 % des captures totales du Sénégal et constitue la principale source de protéines animales pour les ménages. La filière emploie directement 600 000 personnes et fait vivre, indirectement, plusieurs millions de Sénégalais le long du littoral. Le gouverneur de la région a indiqué qu'une réunion de médiation était « en cours de programmation » sans préciser d'heure ni de lieu. À l'heure où nous bouclons cet article, les pirogues sont toujours en travers du chenal." },
    ],
  },
  {
    slug: "touba-magal-5-millions",
    title: "Touba se prépare au grand Magal : 5,2 millions de fidèles attendus",
    dek: "Le comité d'organisation a présenté son dispositif. Hébergement, sécurité, sanitaires : la ville sainte se métamorphose pour accueillir une foule jamais égalée.",
    rubrique: "senegal",
    rubriqueLabel: "Religion · Touba",
    author: "Modou Fall, à Touba",
    date: "Aujourd'hui · 09h00",
    dateIso: "2026-05-07T09:00",
    readTime: "12 min",
    imgSeed: "touba-magal",
    imgAlt: "Touba, préparatifs du grand Magal",
    tags: ["Touba", "Magal", "Religion", "Mouridisme", "Sénégal"],
    authorBio: "Correspondant permanent à Touba, Modou Fall couvre les événements religieux et la vie de la ville sainte depuis 2017.",
    body: [
      { type: "p", text: "À soixante-douze heures du grand Magal de Touba, la ville sainte ressemble à un chantier permanent. Des milliers de bénévoles s'activent pour préparer l'accueil des 5,2 millions de fidèles attendus cette année — un record absolu selon le comité d'organisation." },
      { type: "p", text: "Le dispositif mis en place cette année est le plus ambitieux de l'histoire du Magal. Deux mille points de distribution d'eau potable, sept cents postes de premiers secours, et un système de navettes gratuites depuis les gares routières de Dakar et Thiès ont été organisés." },
      { type: "h2", text: "Une ville qui se métamorphose" },
      { type: "p", text: "Les ruelles de Touba sont méconnaissables. Les grandes artères ont été repavées, les façades badigeonnées de blanc et de vert. Des écrans géants ont été installés aux principaux carrefours pour retransmettre les prières et les sermons en direct." },
      { type: "blockquote", text: "« Touba n'appartient pas à une ville. Elle appartient au monde. »", cite: "Serigne Mountakha Mbacké, Khalife général des Mourides" },
      { type: "h2", text: "Le défi de la sécurité" },
      { type: "p", text: "Quatre mille éléments des forces de sécurité ont été déployés, dont un dispositif spécial de la gendarmerie nationale. La préfecture de Mbacké a mis en place un centre de commandement opérationnel ouvert vingt-quatre heures sur vingt-quatre pendant toute la durée du pèlerinage." },
    ],
  },
  {
    slug: "ziguinchor-accord-paix",
    title: "À Ziguinchor, un accord met fin à 40 ans de conflit",
    dek: "Les représentants du Mouvement des Forces Démocratiques de Casamance et du gouvernement sénégalais ont signé un accord de paix définitif.",
    rubrique: "senegal",
    rubriqueLabel: "Casamance",
    author: "Ousmane Baldé",
    date: "Hier · 21h12",
    dateIso: "2026-05-06T21:12",
    readTime: "6 min",
    imgSeed: "ziguinchor-paix",
    imgAlt: "Ziguinchor, Casamance",
  },
  {
    slug: "brt-dakar-bilan",
    title: "Le BRT change le quotidien à Dakar — premier bilan, six mois après",
    dek: "Moins d'embouteillages sur l'axe Guédiawaye–Petersen, des usagers conquis mais des lacunes dans la desserte des quartiers périphériques.",
    rubrique: "senegal",
    rubriqueLabel: "Mobilité · Dakar",
    author: "Fatou Diallo",
    date: "Aujourd'hui · 08h44",
    dateIso: "2026-05-07T08:44",
    readTime: "5 min",
    imgSeed: "brt-dakar",
    imgAlt: "BRT Dakar",
  },
  {
    slug: "sweet-beauty-appel",
    title: "Affaire Sweet Beauty : la cour d'appel rendra sa décision vendredi",
    dek: "Les avocats des deux parties ont déposé leurs conclusions. Le verdict est attendu après deux ans de procédure.",
    rubrique: "senegal",
    rubriqueLabel: "Justice",
    author: "Service Juridique",
    date: "Aujourd'hui · 07h20",
    dateIso: "2026-05-07T07:20",
    readTime: "3 min",
    imgSeed: "justice-tribunal",
    imgAlt: "Tribunal de Dakar",
  },
  {
    slug: "mboro-phosphates-nappes",
    title: "Mboro : les phosphates relancent l'emploi mais inquiètent les nappes",
    dek: "La reprise des exploitations dans la région de Thiès génère 4 200 emplois directs. Mais les associations de riverains alertent sur la contamination des eaux souterraines.",
    rubrique: "senegal",
    rubriqueLabel: "Économie · Thiès",
    author: "Ibrahima Niang",
    date: "Hier",
    dateIso: "2026-05-06",
    readTime: "Long format",
    imgSeed: "mboro-phosphates",
    imgAlt: "Mboro, mines de phosphates",
    badge: "longformat",
  },

  // ── POLITIQUE ──
  {
    slug: "diomaye-2026-jeunes",
    title: "Plan Diomaye 2026 : ce que le gouvernement promet aux jeunes diplômés",
    dek: "160 milliards FCFA, 75 000 contrats, mais beaucoup d'inconnues sur le calendrier et les critères de sélection.",
    rubrique: "politique",
    rubriqueLabel: "Politique",
    author: "Service Politique",
    date: "Il y a 1h",
    dateIso: "2026-05-07T12:00",
    readTime: "4 min",
    imgSeed: "diomaye-jeunes",
    imgAlt: "Plan Diomaye 2026",
  },
  {
    slug: "opposition-conseil-constitutionnel",
    title: "L'opposition demande une réforme du Conseil constitutionnel",
    dek: "Treize partis d'opposition ont signé une pétition commune réclamant la révision du mode de nomination des membres du Conseil.",
    rubrique: "politique",
    rubriqueLabel: "Politique",
    author: "Rokhaya Diop",
    date: "11h08",
    dateIso: "2026-05-07T11:08",
    readTime: "3 min",
    imgSeed: "conseil-constitutionnel",
    imgAlt: "Conseil constitutionnel du Sénégal",
  },
  {
    slug: "diomaye-paris-agenda",
    title: "Diomaye Faye à Paris : ce que prévoit l'agenda du président",
    dek: "Trois jours de réunions bilatérales, un discours à Sciences Po et une rencontre avec la diaspora sénégalaise en France.",
    rubrique: "politique",
    rubriqueLabel: "Politique · Diplomatie",
    author: "Service Politique",
    date: "Hier",
    dateIso: "2026-05-06",
    readTime: "4 min",
    imgSeed: "diomaye-paris",
    imgAlt: "Diomaye Faye à Paris",
  },

  // ── ÉCONOMIE ──
  {
    slug: "gaz-gta-phase-2",
    title: "Gaz GTA : la phase 2 d'exploitation entre dans le calendrier officiel",
    dek: "BP et Kosmos confirment une mise en production progressive début 2027. Les recettes pour l'État sénégalais sont revues à la hausse.",
    rubrique: "economie",
    rubriqueLabel: "Économie · Énergie",
    author: "Cheikh Sarr",
    date: "Il y a 2h",
    dateIso: "2026-05-07T11:00",
    readTime: "5 min",
    imgSeed: "gaz-gta",
    imgAlt: "Plateforme gazière GTA",
    tags: ["Gaz naturel", "GTA", "BP", "Énergie", "Économie"],
    authorBio: "Cheikh Sarr est journaliste économique spécialisé dans les industries extractives. Il suit le dossier pétrole-gaz au Sénégal depuis 2021.",
    body: [
      { type: "p", text: "BP et Kosmos Energy ont confirmé mercredi que la phase 2 du projet gazier Grand Tortue Ahmeyim (GTA) est désormais inscrite dans leur planning officiel, avec une mise en production progressive attendue au premier trimestre 2027. L'annonce, faite en marge d'une conférence à Dakar, constitue une bonne nouvelle pour les finances publiques sénégalaises." },
      { type: "p", text: "Les recettes attendues pour l'État sénégalais ont été révisées à la hausse : selon le ministère du Pétrole, les exportations de la phase 2 pourraient générer entre 280 et 340 milliards de francs CFA par an, soit près du double des projections initiales, grâce à la hausse des prix du GNL sur les marchés asiatiques." },
      { type: "h2", text: "Un projet complexe, enfin sur les rails" },
      { type: "p", text: "GTA, développé à cheval sur les eaux territoriales sénégalaises et mauritaniennes, est l'un des projets gaziers les plus complexes d'Afrique de l'Ouest. La phase 1, entrée en production fin 2024, produit environ 2,4 millions de tonnes de GNL par an. La phase 2 devrait doubler cette capacité." },
      { type: "pullquote", text: "Le Sénégal entre dans l'ère des grandes exportations énergétiques. Le défi est désormais de transformer cette rente en développement durable." },
    ],
  },
  {
    slug: "bceao-franc-cfa",
    title: "Le franc CFA de nouveau au centre des discussions à la BCEAO",
    dek: "Lors de la réunion trimestrielle d'Abidjan, plusieurs gouverneurs ont évoqué la nécessité d'une réforme du régime de change.",
    rubrique: "economie",
    rubriqueLabel: "Économie",
    author: "Aminata Traoré",
    date: "10h42",
    dateIso: "2026-05-07T10:42",
    readTime: "5 min",
    imgSeed: "bceao-fcfa",
    imgAlt: "BCEAO, franc CFA",
  },
  {
    slug: "petrole-senegal-rente",
    title: "Pétrole sénégalais : à qui profite réellement la rente ?",
    dek: "Six mois après le début des exportations de Sangomar, une enquête exclusive sur la distribution des revenus pétroliers.",
    rubrique: "economie",
    rubriqueLabel: "Économie · Énergie",
    author: "Mamadou Diallo",
    date: "Lundi",
    dateIso: "2026-05-04",
    readTime: "22 min",
    imgSeed: "dossier-petrole",
    imgAlt: "Plateforme pétrolière Sangomar",
    badge: "longformat",
    featured: true,
  },

  // ── AFRIQUE ──
  {
    slug: "presidentielle-ivoirienne-manouvres",
    title: "Présidentielle ivoirienne : les dernières manœuvres avant le scrutin d'octobre",
    dek: "Alliances de dernière minute, retours sur la scène politique : Abidjan vit sous tension électorale permanente.",
    rubrique: "afrique",
    rubriqueLabel: "Côte d'Ivoire",
    author: "Bureau d'Abidjan",
    date: "Il y a 3h",
    dateIso: "2026-05-07T10:00",
    readTime: "6 min",
    imgSeed: "ivoire-presidentielle",
    imgAlt: "Présidentielle en Côte d'Ivoire",
    featured: true,
  },
  {
    slug: "attentat-bamako",
    title: "Un nouvel attentat secoue Bamako, 14 morts dans une caserne",
    dek: "Une voiture piégée a explosé aux abords d'une caserne militaire dans la banlieue nord de la capitale malienne.",
    rubrique: "afrique",
    rubriqueLabel: "Sahel · Mali",
    author: "Correspondant à Dakar",
    date: "06h14",
    dateIso: "2026-05-07T06:14",
    readTime: "4 min",
    imgSeed: "sahel-bamako",
    imgAlt: "Bamako, Mali",
  },
  {
    slug: "cedeao-urgence-defense",
    title: "CEDEAO — réunion d'urgence des ministres de la défense vendredi à Abuja",
    dek: "Face à la recrudescence des attaques terroristes au Sahel, les quinze États membres de la CEDEAO se retrouvent en sommet extraordinaire.",
    rubrique: "afrique",
    rubriqueLabel: "CEDEAO",
    author: "Service Afrique",
    date: "12h31",
    dateIso: "2026-05-07T12:31",
    readTime: "3 min",
    imgSeed: "cedeao-abuja",
    imgAlt: "CEDEAO, réunion à Abuja",
  },
  {
    slug: "rdc-treve-goma",
    title: "La trêve dans l'Est de la RDC tient pour la troisième semaine consécutive",
    dek: "Les observateurs de l'ONU notent une baisse significative des incidents armés dans la région de Goma depuis l'accord de Luanda.",
    rubrique: "afrique",
    rubriqueLabel: "RDC · Goma",
    author: "Correspondant à Kinshasa",
    date: "Hier",
    dateIso: "2026-05-06",
    readTime: "4 min",
    imgSeed: "rdc-paix",
    imgAlt: "Goma, RDC",
  },

  // ── SOCIÉTÉ ──
  {
    slug: "keur-massar-inondations",
    title: "Inondations à Keur Massar : l'État active le plan ORSEC",
    dek: "Les quartiers de Keur Massar Nord et Jaxaay sont sous les eaux depuis hier soir. L'armée est déployée pour les évacuations.",
    rubrique: "societe",
    rubriqueLabel: "Société",
    author: "Seydina Diagne",
    date: "09h30",
    dateIso: "2026-05-07T09:30",
    readTime: "3 min",
    imgSeed: "keurmassar-pluies",
    imgAlt: "Inondations à Keur Massar",
    badge: "live",
  },
  {
    slug: "mbour-familles-migrants",
    title: "« Nous sommes fatigués » : à Mbour, la colère des familles de migrants disparus",
    dek: "Trois ans après la disparition de leurs proches en mer, des familles de Mbour réclament une enquête indépendante sur les conditions des traversées.",
    rubrique: "societe",
    rubriqueLabel: "Société · Mbour",
    author: "Aminata Seck",
    date: "Hier",
    dateIso: "2026-05-06",
    readTime: "12 min",
    imgSeed: "mbour-migrants",
    imgAlt: "Mbour, familles de migrants",
  },

  // ── SPORT ──
  {
    slug: "lions-selection-mane",
    title: "Mané, Sarr, Koulibaly : la liste qui fait vibrer la Téranga",
    dek: "Le sélectionneur Aliou Cissé a convoqué 26 joueurs pour les qualifications à la CAN 2027. Sadio Mané fait son retour.",
    rubrique: "sport",
    rubriqueLabel: "Football · Lions",
    author: "Édition Sport",
    date: "Aujourd'hui",
    dateIso: "2026-05-07",
    readTime: "5 min",
    imgSeed: "lions-teranga",
    imgAlt: "Lions de la Téranga",
  },
  {
    slug: "lutte-modou-lo-siteu",
    title: "Modou Lô vs Siteu : la revanche que tout Dakar attend",
    dek: "Deux ans après leur premier duel, les deux rois de l'arène s'affrontent de nouveau le 14 juin à l'arène nationale.",
    rubrique: "sport",
    rubriqueLabel: "Lutte sénégalaise",
    author: "Pape Sow",
    date: "Hier",
    dateIso: "2026-05-06",
    readTime: "6 min",
    imgSeed: "lutte-modou-lo",
    imgAlt: "Lutte sénégalaise, Modou Lô",
  },

  // ── CULTURE ──
  {
    slug: "youssou-ndour-tournee",
    title: "Youssou Ndour annonce une tournée à travers cinq pays africains",
    dek: "De Dakar à Nairobi, le chanteur sénégalais présentera son nouvel album « Xippi » dans cinq capitales africaines cet été.",
    rubrique: "culture",
    rubriqueLabel: "Culture",
    author: "Service Culture",
    date: "09h15",
    dateIso: "2026-05-07T09:15",
    readTime: "3 min",
    imgSeed: "youssou-ndour",
    imgAlt: "Youssou Ndour",
    badge: "video",
  },
  {
    slug: "dakart-biennale-2026",
    title: "La Biennale de Dakar 2026 dévoile sa direction artistique",
    dek: "L'artiste Ndary Lo prendra la tête de la prochaine Biennale, avec pour thème central « Mémoires plurielles, futurs communs ».",
    rubrique: "culture",
    rubriqueLabel: "Arts · Dak'Art",
    author: "Marie-Hélène Badji",
    date: "Mardi",
    dateIso: "2026-05-05",
    readTime: "4 min",
    imgSeed: "dakar-biennale",
    imgAlt: "Biennale de Dakar, Dak'Art 2026",
  },
  {
    slug: "mati-diop-cannes",
    title: "Mati Diop, Cannes, et la nouvelle vague sénégalaise",
    dek: "Avec son troisième long-métrage en sélection officielle, la cinéaste sénégalaise confirme sa place parmi les voix les plus originales du cinéma mondial.",
    rubrique: "culture",
    rubriqueLabel: "Cinéma",
    author: "Sokhna Fall",
    date: "Lundi",
    dateIso: "2026-05-04",
    readTime: "7 min",
    imgSeed: "cinema-mati-diop",
    imgAlt: "Mati Diop, cinéaste sénégalaise",
    badge: "video",
  },
  {
    slug: "bouba-ndour-festival-saint-louis",
    title: "Bouba Ndour réagit aux critiques sur le festival de Saint-Louis",
    dek: "Face aux accusations de mauvaise gestion, le directeur artistique du Jazz Festival de Saint-Louis publie un communiqué détaillé.",
    rubrique: "culture",
    rubriqueLabel: "Culture · Festival",
    author: "Service Culture",
    date: "Hier",
    dateIso: "2026-05-06",
    readTime: "5 min",
    imgSeed: "festival-saint-louis",
    imgAlt: "Festival de Jazz de Saint-Louis",
  },

  // ── DIASPORA ──
  {
    slug: "marseille-senegalais-legislatives",
    title: "À Marseille, les Sénégalais préparent les législatives — entre fierté et fatigue",
    dek: "Reportage dans la communauté sénégalaise de Marseille à quelques semaines des élections législatives.",
    rubrique: "diaspora",
    rubriqueLabel: "Diaspora · Marseille",
    author: "Bineta Sy, envoyée spéciale",
    date: "Ce matin",
    dateIso: "2026-05-07T08:00",
    readTime: "8 min",
    imgSeed: "marseille-diaspora",
    imgAlt: "Communauté sénégalaise à Marseille",
    badge: "video",
  },
  {
    slug: "diaspora-vote-pourquoi",
    title: "Pourquoi la diaspora doit voter — vraiment",
    dek: "Tribune de Rama Yade : comment les 3 millions de Sénégalais de l'extérieur peuvent peser dans les urnes et dans les politiques publiques.",
    rubrique: "diaspora",
    rubriqueLabel: "Diaspora · Tribune",
    author: "Rama Yade",
    date: "Lundi",
    dateIso: "2026-05-04",
    readTime: "6 min",
    imgSeed: "diaspora-vote",
    imgAlt: "Vote diaspora sénégalaise",
  },
];

export const PODCASTS: Podcast[] = [
  {
    letter: "D", variant: "",
    show: "Les Décodeurs",
    title: "La CEDEAO peut-elle survivre au départ du Mali, du Burkina et du Niger ?",
    duration: "28 min",
    date: "Hier",
  },
  {
    letter: "T", variant: "b",
    show: "Téranga · Le portrait",
    title: "Aïssata Tall Sall : « la diplomatie sénégalaise se réinvente »",
    duration: "42 min",
    date: "Cette semaine",
  },
  {
    letter: "É", variant: "g",
    show: "Économie d'Afrique",
    title: "Pétrole sénégalais : à qui profite réellement la rente ?",
    duration: "35 min",
    date: "Lundi",
  },
];

export function getArticlesByRubrique(slug: string): Article[] {
  return ARTICLES.filter((a) => a.rubrique === slug);
}

export function getArticleBySlug(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

export function getFeaturedArticle(): Article {
  return ARTICLES.find((a) => a.featured && a.rubrique === "senegal") ?? ARTICLES[0];
}

export function getAlaUne(): Article[] {
  const picks: Article["rubrique"][] = ["politique", "economie", "societe", "culture"];
  return picks.map((r) => ARTICLES.find((a) => a.rubrique === r)!).filter(Boolean);
}
